# Generated by Django 5.2.1 on 2026-02-06 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_clerk_and_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cuisine', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inventory_status', models.CharField(default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='user.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'user'), name='unique_menu_item_per_user')],
            },
        ),
    ]
