# Generated by Django 4.2.20 on 2025-04-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
