# Generated by Django 4.2.20 on 2025-05-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory_status',
            field=models.CharField(default='in_stock', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
