# Generated by Django 4.2.20 on 2025-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitem', '0003_menuitem_inventory_status_menuitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.CharField(default='', max_length=100),
        ),
    ]
