apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: django-backend
  labels:
    io.kompose.service: pgdata
  name: pgdata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
status: {}
