apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: django-backend
  labels:
    io.kompose.service: web-claim0
  name: web-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

status: {}
