# Generated by Django 5.2.1 on 2026-05-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_clerk_and_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
