# Generated by Django 5.2.1 on 2026-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_number_of_orders_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clerk_user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
